# Generated by Django 3.2.12 on 2022-09-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
